# Generated by Django 4.2.9 on 2026-03-16 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('user_role', models.CharField(blank=True, max_length=20)),
                ('dept_name', models.CharField(blank=True, max_length=120)),
                ('action', models.CharField(choices=[('file_view', 'Visualizou ficheiro'), ('file_create', 'Criou ficheiro'), ('file_edit', 'Editou ficheiro'), ('file_delete', 'Eliminou ficheiro'), ('file_restore', 'Restaurou ficheiro'), ('file_download', 'Descarregou ficheiro'), ('folder_create', 'Criou pasta'), ('folder_delete', 'Eliminou pasta'), ('perm_grant', 'Concedeu permissão'), ('perm_revoke', 'Revogou permissão'), ('login', 'Iniciou sessão'), ('logout', 'Terminou sessão'), ('login_failed', 'Falha no login'), ('perm_denied', 'Acesso negado'), ('user_create', 'Criou utilizador'), ('dept_create', 'Criou departamento')], max_length=20)),
                ('result', models.CharField(choices=[('success', 'Sucesso'), ('denied', 'Negado'), ('error', 'Erro')], default='success', max_length=10)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('node_name', models.CharField(blank=True, max_length=255)),
                ('node_path', models.CharField(blank=True, max_length=2048)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounts.department')),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='files.filesystemnode')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='audit_audit_user_id_e8be02_idx'), models.Index(fields=['node', 'timestamp'], name='audit_audit_node_id_4c730b_idx'), models.Index(fields=['action', 'result'], name='audit_audit_action_4c922e_idx'), models.Index(fields=['department', 'timestamp'], name='audit_audit_departm_aa037c_idx')],
            },
        ),
    ]
