# Generated by Django 6.0.6 on 2026-07-20 15:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def create_default_company(apps, schema_editor):
    """Create a default company for existing departments"""
    Company = apps.get_model('accounts', 'Company')
    Department = apps.get_model('accounts', 'Department')
    
    # Create default company
    default_company = Company.objects.create(
        name='Default Company',
        slug='default-company',
        description='Default company for existing departments'
    )
    
    # Assign all existing departments to this company
    Department.objects.all().update(company=default_company)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['company', 'name']},
        ),
        migrations.AlterField(
            model_name='crossdeptpermission',
            name='granted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_dept_granted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(max_length=80),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('quota_bytes', models.BigIntegerField(default=10737418240)),
                ('used_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'super_admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='accounts.company'),
        ),
        migrations.RunPython(create_default_company, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='department',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.company'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('company', 'name'), ('company', 'slug')},
        ),
        migrations.RemoveField(
            model_name='department',
            name='quota_bytes',
        ),
        migrations.RemoveField(
            model_name='department',
            name='used_bytes',
        ),
    ]
