# Generated by Django 4.2.9 on 2026-03-16 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSystemNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('node_type', models.CharField(choices=[('folder', 'Pasta'), ('file', 'Ficheiro')], default='folder', max_length=6)),
                ('materialized_path', models.CharField(db_index=True, max_length=2048)),
                ('file_field', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/')),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('extension', models.CharField(blank=True, max_length=20)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('is_starred', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes_deleted', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='accounts.department')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='files.filesystemnode')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['node_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserFilePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission_mask', models.IntegerField(default=1)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_assigned', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='files.filesystemnode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'node', 'is_active'], name='files_userf_user_id_b371fa_idx')],
                'unique_together': {('user', 'node')},
            },
        ),
        migrations.AddIndex(
            model_name='filesystemnode',
            index=models.Index(fields=['department', 'materialized_path'], name='files_files_departm_488efb_idx'),
        ),
        migrations.AddIndex(
            model_name='filesystemnode',
            index=models.Index(fields=['parent', 'name'], name='files_files_parent__0c90c6_idx'),
        ),
        migrations.AddIndex(
            model_name='filesystemnode',
            index=models.Index(fields=['node_type', 'department'], name='files_files_node_ty_9109c4_idx'),
        ),
        migrations.AddIndex(
            model_name='filesystemnode',
            index=models.Index(fields=['is_deleted', 'department'], name='files_files_is_dele_1e86ab_idx'),
        ),
        migrations.AddConstraint(
            model_name='filesystemnode',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('parent', 'name', 'department'), name='unique_name_in_parent'),
        ),
    ]
