# Generated by Django 4.2.9 on 2026-07-09 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesystemnode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='files.filesystemnode'),
        ),
        migrations.AlterField(
            model_name='userfilepermission',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='filesystemnode',
            index=models.Index(fields=['department', 'name'], name='files_files_departm_d7c775_idx'),
        ),
    ]
