# Generated by Django 6.0.6 on 2026-07-20 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_default_company(apps, schema_editor):
    """Assign default company to existing filesystem nodes"""
    Company = apps.get_model('accounts', 'Company')
    FileSystemNode = apps.get_model('files', 'FileSystemNode')
    
    # Get the default company created in accounts migration
    default_company = Company.objects.filter(slug='default-company').first()
    if default_company:
        FileSystemNode.objects.all().update(company=default_company)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_department_options_and_more'),
        ('files', '0002_alter_filesystemnode_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='filesystemnode',
            name='unique_name_in_parent',
        ),
        migrations.RemoveIndex(
            model_name='filesystemnode',
            name='files_files_node_ty_9109c4_idx',
        ),
        migrations.RemoveIndex(
            model_name='filesystemnode',
            name='files_files_is_dele_1e86ab_idx',
        ),
        migrations.RemoveIndex(
            model_name='filesystemnode',
            name='files_files_departm_d7c775_idx',
        ),
        migrations.AddField(
            model_name='filesystemnode',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='accounts.company'),
        ),
        migrations.RunPython(assign_default_company, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='filesystemnode',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='filesystemnode',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='accounts.department'),
        ),
        migrations.AddIndex(
            model_name='filesystemnode',
            index=models.Index(fields=['company', 'materialized_path'], name='files_files_company_561b4d_idx'),
        ),
        migrations.AddIndex(
            model_name='filesystemnode',
            index=models.Index(fields=['node_type', 'company'], name='files_files_node_ty_e4cb52_idx'),
        ),
        migrations.AddIndex(
            model_name='filesystemnode',
            index=models.Index(fields=['is_deleted', 'company'], name='files_files_is_dele_dd6b08_idx'),
        ),
        migrations.AddIndex(
            model_name='filesystemnode',
            index=models.Index(fields=['company', 'name'], name='files_files_company_e8450b_idx'),
        ),
        migrations.AddConstraint(
            model_name='filesystemnode',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('parent', 'name', 'company'), name='unique_name_in_parent'),
        ),
    ]
