# Generated by Django 6.0.6 on 2026-07-20 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_remove_filesystemnode_unique_name_in_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfilepermission',
            options={'ordering': ['-assigned_at']},
        ),
        migrations.AlterField(
            model_name='filesystemnode',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='filesystemnode',
            name='materialized_path',
            field=models.CharField(blank=True, db_index=True, max_length=2048),
        ),
    ]
