# Generated by Django 6.0.6 on 2026-07-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_alter_userfilepermission_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesystemnode',
            name='content',
            field=models.TextField(blank=True, help_text='HTML content for document editor'),
        ),
    ]
