# Generated by Django 6.0.6 on 2026-07-22 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_company_created_by'),
        ('files', '0006_filelock_and_group_permissions'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='groupfilepermission',
            name='unique_group_node_permission',
        ),
        migrations.RenameIndex(
            model_name='filelock',
            new_name='files_filel_node_id_f1e60f_idx',
            old_name='files_file_2b8f5a_idx',
        ),
        migrations.RenameIndex(
            model_name='filelock',
            new_name='files_filel_locked__db3d46_idx',
            old_name='files_file_5e8f5a_idx',
        ),
        migrations.RenameIndex(
            model_name='filelock',
            new_name='files_filel_expires_28d44a_idx',
            old_name='files_file_6e8f5a_idx',
        ),
        migrations.RenameIndex(
            model_name='groupfilepermission',
            new_name='files_group_group_i_c66d47_idx',
            old_name='files_grou_7e8f5a_idx',
        ),
        migrations.AlterUniqueTogether(
            name='groupfilepermission',
            unique_together={('group', 'node')},
        ),
    ]
